import {
  TraceProfile,
  EvidenceItem,
  TimelineEvent,
  ResearchSet,
} from '@shared/index';

export const SAMPLE_EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: 'ev-msft-offer',
    type: 'dom_text',
    factState: 'observed',
    rawText: 'Incoming Software Development Engineer @ Microsoft accepted full-time offer starting 2026.',
    provenance: {
      url: 'https://linkedin.com/in/ashmit-bagga',
      pageTitle: 'Ashmit Bagga | LinkedIn',
      capturedAt: '2026-09-03T08:15:00.000Z',
      domSelector: '.pv-text-details__left-panel h2',
      contextSnippet: 'Incoming SDE @ Microsoft | XYZ Institute of Technology · B.Tech CS (2022–2026)',
    },
    extractedAt: '2026-09-03T08:15:00.000Z',
    confidence: 'high',
    annotation: 'Confirmed via LinkedIn profile headline and verified placement announcement.',
  },
  {
    id: 'ev-flipkart',
    type: 'dom_text',
    factState: 'observed',
    rawText: 'Software Development Engineer Intern at Flipkart (Core Backend Platform Team), May 2025 – Jul 2025.',
    provenance: {
      url: 'https://linkedin.com/in/ashmit-bagga/details/experience',
      pageTitle: 'Ashmit Bagga - Experience | LinkedIn',
      capturedAt: '2026-09-03T08:15:00.000Z',
      contextSnippet: 'Kafka consumer group re-balancing optimization reducing p99 processing lag by 34%. Architected high-throughput Golang telemetry proxy.',
    },
    extractedAt: '2026-09-03T08:15:00.000Z',
    confidence: 'high',
  },
  {
    id: 'ev-techflow',
    type: 'dom_text',
    factState: 'observed',
    rawText: 'Software Engineering Intern at TechFlow Solutions, May 2024 – Jul 2024.',
    provenance: {
      url: 'https://linkedin.com/in/ashmit-bagga/details/experience',
      pageTitle: 'Ashmit Bagga - Experience | LinkedIn',
      capturedAt: '2026-09-03T08:15:00.000Z',
      contextSnippet: 'Built internal dashboard and REST APIs using React, TypeScript, and Go.',
    },
    extractedAt: '2026-09-03T08:15:00.000Z',
    confidence: 'high',
  },
  {
    id: 'ev-leetcode-527',
    type: 'dom_text',
    factState: 'observed',
    rawText: '527 LeetCode problems solved & 45-day continuous streak (Peak Rating 1,984 across 26 contests).',
    provenance: {
      url: 'https://leetcode.com/ashmit_b',
      pageTitle: 'Ashmit Bagga - LeetCode Profile',
      capturedAt: '2026-09-03T08:16:00.000Z',
      contextSnippet: 'Easy (190), Medium (280), Hard (57). Peak contest rating 1984.',
    },
    extractedAt: '2026-09-03T08:16:00.000Z',
    confidence: 'high',
  },
  {
    id: 'ev-sih-winner',
    type: 'dom_text',
    factState: 'observed',
    rawText: '1st Place National Winner, Smart India Hackathon (SIH 2024).',
    provenance: {
      url: 'https://linkedin.com/in/ashmit-bagga/details/honors',
      pageTitle: 'Ashmit Bagga - Honors | LinkedIn',
      capturedAt: '2026-09-03T08:15:00.000Z',
      contextSnippet: 'Smart India Hackathon 2024 winner for automated logistics route planning system.',
    },
    extractedAt: '2026-09-03T08:15:00.000Z',
    confidence: 'high',
  },
  {
    id: 'ev-kafka-pr',
    type: 'dom_text',
    factState: 'observed',
    rawText: 'Merged upstream PR #418 on github.com/confluentinc/confluent-kafka-go.',
    provenance: {
      url: 'https://github.com/confluentinc/confluent-kafka-go/pull/418',
      pageTitle: 'Pull Request #418 · confluent-kafka-go',
      capturedAt: '2026-09-03T08:16:30.000Z',
      contextSnippet: 'Fix consumer partition assignment batch sizes and add telemetry handlers.',
    },
    extractedAt: '2026-09-03T08:16:30.000Z',
    confidence: 'high',
  },
];

export const SAMPLE_PROFILE: TraceProfile = {
  id: 'profile-ashmit-bagga',
  sourceUrl: 'https://www.linkedin.com/in/ashmit-bagga',
  fullName: 'Ashmit Bagga',
  headline: 'Incoming SDE @ Microsoft',
  location: 'New Delhi, India',
  aboutSummary:
    'Senior CS undergraduate at XYZ Institute of Technology with focused experience in distributed systems, backend infrastructure in Go, and high-volume competitive programming.',
  capturedAt: '2026-09-03T08:15:00.000Z',
  updatedAt: '2026-09-03T08:33:00.000Z',
  experiences: [
    {
      id: 'exp-1',
      title: 'SDE Intern',
      companyName: 'Flipkart',
      companyUrl: 'https://flipkart.com',
      location: 'Bangalore, India',
      dateRange: {
        startDate: 'May 2025',
        endDate: 'Jul 2025',
        isCurrent: false,
        rawString: 'May 2025 – Jul 2025 · 3 months',
      },
      description:
        'Core Backend Platform Team: Kafka consumer group re-balancing optimization reducing p99 processing lag by 34%. Architected high-throughput Golang telemetry proxy for service mesh monitoring.',
      factState: 'observed',
      evidenceIds: ['ev-flipkart'],
      skillsMentioned: ['Go', 'Kafka', 'Distributed Systems'],
    },
    {
      id: 'exp-2',
      title: 'Software Engineering Intern',
      companyName: 'TechFlow Solutions',
      location: 'New Delhi, India',
      dateRange: {
        startDate: 'May 2024',
        endDate: 'Jul 2024',
        isCurrent: false,
        rawString: 'May 2024 – Jul 2024 · 3 months',
      },
      description:
        'Full-stack engineering: Engineered customer-facing analytics dashboards using React, TypeScript, and Go microservices.',
      factState: 'observed',
      evidenceIds: ['ev-techflow'],
      skillsMentioned: ['React', 'TypeScript', 'Go', 'REST APIs'],
    },
  ],
  education: [
    {
      id: 'edu-1',
      schoolName: 'XYZ Institute of Technology',
      degree: 'B.Tech in Computer Science and Engineering',
      fieldOfStudy: 'Computer Science',
      dateRange: {
        startDate: '2022',
        endDate: '2026',
        isCurrent: true,
        rawString: '2022–2026',
      },
      factState: 'observed',
      evidenceIds: ['ev-msft-offer'],
    },
  ],
  skills: [
    {
      id: 'sk-1',
      name: 'Data Structures & Algorithms',
      category: 'Problem Solving',
      factState: 'observed',
      associatedItemIds: ['exp-1'],
      evidenceIds: ['ev-leetcode-527'],
      qualitativeAssessment: {
        confidence: 'high',
        context: '527 solved problems, 26 contests, peak 1,984 rating.',
      },
    },
    {
      id: 'sk-2',
      name: 'Distributed Systems & Microservices',
      category: 'Backend Architecture',
      factState: 'observed',
      associatedItemIds: ['exp-1'],
      evidenceIds: ['ev-flipkart'],
      qualitativeAssessment: {
        confidence: 'high',
        context: 'Kafka consumer group optimization reducing p99 latency.',
      },
    },
    {
      id: 'sk-3',
      name: 'Golang & Concurrency',
      category: 'Languages & Runtimes',
      factState: 'observed',
      associatedItemIds: ['exp-1', 'exp-2'],
      evidenceIds: ['ev-flipkart', 'ev-kafka-pr'],
    },
    {
      id: 'sk-4',
      name: 'Production System Design',
      category: 'System Architecture',
      factState: 'inferred',
      associatedItemIds: ['exp-1'],
      evidenceIds: ['ev-flipkart'],
      qualitativeAssessment: {
        confidence: 'medium',
        context: 'Inferred from high-throughput reverse proxy and Kafka pub/sub tuning.',
      },
    },
  ],
  certifications: [],
  publications: [
    {
      id: 'pub-1',
      title: 'High-Throughput Golang Telemetry Proxy for Service Mesh',
      publisher: 'GitHub / Tech Blog',
      publicationDate: '2025',
      url: 'https://github.com/ashmit-b/telemetry-proxy',
      evidenceIds: ['ev-flipkart'],
    },
  ],
  evidenceIds: [
    'ev-msft-offer',
    'ev-flipkart',
    'ev-techflow',
    'ev-leetcode-527',
    'ev-sih-winner',
    'ev-kafka-pr',
  ],
  metadata: {
    extractionVersion: '0.1.0',
    totalEvidenceCount: 6,
    notes: 'Sample verified trajectory loaded from Stitch design template.',
  },
};

export const SAMPLE_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'tl-1',
    sourceItemId: 'msft-offer',
    category: 'career',
    title: 'Software Development Engineer',
    organization: 'Microsoft',
    startDate: 'Oct 2025',
    isCurrent: false,
    description: 'Full-time offer accepted · Bangalore/Hyderabad.',
    factState: 'observed',
    evidenceIds: ['ev-msft-offer'],
  },
  {
    id: 'tl-2',
    sourceItemId: 'system-design',
    category: 'milestone',
    title: 'Core System Design Preparation',
    organization: 'Self-Directed',
    startDate: 'Late 2025',
    isCurrent: false,
    description: 'Distributed systems, database sharding, and microservices synthesis.',
    factState: 'unknown',
    evidenceIds: [],
  },
  {
    id: 'tl-3',
    sourceItemId: 'exp-1',
    category: 'career',
    title: 'SDE Intern',
    organization: 'Flipkart',
    startDate: 'May 2025',
    endDate: 'Jul 2025',
    isCurrent: false,
    description: 'Core Backend Platform: Kafka consumer re-balancing reducing p99 processing lag by 34%.',
    factState: 'observed',
    evidenceIds: ['ev-flipkart'],
  },
  {
    id: 'tl-4',
    sourceItemId: 'sih',
    category: 'milestone',
    title: 'Smart India Hackathon Winner',
    organization: 'Ministry of Education',
    startDate: 'Dec 2024',
    isCurrent: false,
    description: 'National 1st prize for automated logistics dispatch engine.',
    factState: 'observed',
    evidenceIds: ['ev-sih-winner'],
  },
  {
    id: 'tl-5',
    sourceItemId: 'exp-2',
    category: 'career',
    title: 'Software Engineering Intern',
    organization: 'TechFlow Solutions',
    startDate: 'May 2024',
    endDate: 'Jul 2024',
    isCurrent: false,
    description: 'Frontend telemetry dashboards with React/TypeScript and Go microservices.',
    factState: 'observed',
    evidenceIds: ['ev-techflow'],
  },
  {
    id: 'tl-6',
    sourceItemId: 'edu-1',
    category: 'education',
    title: 'B.Tech in Computer Science',
    organization: 'XYZ Institute of Technology',
    startDate: 'Oct 2022',
    endDate: 'Jun 2026',
    isCurrent: true,
    description: 'Core coursework: Algorithms, OS, Computer Networks, Database Systems.',
    factState: 'observed',
    evidenceIds: ['ev-msft-offer'],
  },
];

export const SAMPLE_RESEARCH_SETS: ResearchSet[] = [
  {
    id: 'set-tier1-sde',
    title: 'Tier-1 Campus SDE Cohort (Batch 2026)',
    description: 'Undergraduate candidates securing Big Tech full-time SDE placements.',
    createdAt: '2026-09-03T08:00:00.000Z',
    updatedAt: '2026-09-03T08:30:00.000Z',
    tags: ['BigTech', 'Campus2026', 'Backend'],
    profileRefs: [
      {
        profileId: 'profile-ashmit-bagga',
        fullName: 'Ashmit Bagga',
        headline: 'Incoming SDE @ Microsoft',
        addedAt: '2026-09-03T08:30:00.000Z',
        tags: ['Microsoft', 'Flipkart', 'DSA-Peak'],
      },
    ],
  },
];
